name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
            
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
            
    - name: Print version
      uses: actions-rs/cargo@v1
      with:
        command: version
        args: -v

    - name: Print tree
      uses: actions-rs/cargo@v1
      with:
        command: tree
      
    - name: Run cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - uses: actions/upload-artifact@v2
      with:
        name: linux-x64
        path: target/release/assembly-lines
