name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install openssl
      run: sudo apt-get install pkg-config libssl-dev
      
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose

    - uses: actions/upload-artifact@v2
      with:
        name: linux-x64
        path: target/release/assembly-lines
